### ISSUE TITLE
Chinese character misplacement 

### ISSUE THREAD

**Issue by sjlei** [TomasHubelbauer/vscode-markdown-table-format#2]
This plugin is great
but support for Chinese characters is not very good. please see the picture below.

![](https://user-images.githubusercontent.com/34293221/54578817-15751a80-4a3c-11e9-900d-ff72c13d0c28.png)

what is this question? How to solve it? Thank you!

------

这个插件做的非常棒！但是对于中文字符的支持不是很好，请看图片，这是什么问题？ 怎么解决？谢谢！

**Comment by TomasHubelbauer** [comment]
I will take a look, thanks for sending the repro case! I am not sure if this is caused by me indexing a string (which I think should be fine in newer versions of JS languages) or if it is because the VS Code API function for getting characters and lines, but I'll try this and find out.

**Comment by sjlei** [comment]
I've found the reason. It's because of the font. When I change to an monospaced font, the problem will be solved.

**Comment by TomasHubelbauer** [comment]
Thanks for reporting this!
